<?php

return [
    'keywords' => [
        'agua',
        'agua con gas',
        'agua saborizada',
        'aquarius',
        'aperol',
        'bebida',
        'bebida deportiva',
        'bebida energizante',
        'bonaqua',
        'branca',
        'campari',
        'cerveza',
        'cinzano',
        'coca',
        'coca cola',
        'coca-cola',
        'coñac',
        'cognac',
        'energético',
        'energetico',
        'espumante',
        'fanta',
        'fernet',
        'gancia',
        'gaseosa',
        'gaseos',
        'gatorade',
        'gin',
        'isotonica',
        'isotónica',
        'jugo',
        'jugo de frutas',
        'licor',
        'monster',
        'moster',
        'néctar',
        'nectar',
        'pepsi',
        'powerade',
        'red bull',
        'refresco',
        'ron',
        'saborizada',
        'schweppes',
        'seven up',
        'sidra',
        'skyy',
        'smirnoff',
        'soda',
        'sprite',
        'tequila',
        'terma',
        'tonica',
        'tónica',
        'vodka',
        'vino',
        'whiskey',
        'whisky',
        '7up',
    ]
];
